name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  github-contribution-grid-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user: your-username
          svg_out_path: github-contribution-grid-snake.svg
